<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.8.3 setup script
 * Date: Wed, 12 Dec 2018 20:50:32 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'localhost';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'root';
$cfg['Servers'][$i]['AllowNoPassword'] = true;

/* End of servers configuration */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['blowfish_secret'] = '^=2nr3:ERLUDvl\'P7ctE)G,0/Gk-]jyq';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>